version: '2'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    networks:
      - appnet
networks:
  appnet:
    driver: "bridge"
