version: '2'
services:
  app:
    image: lkmadushan/nginx-php-alpine
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    networks:
      - appnet
networks:
  appnet:
    driver: "bridge"
